num_worker: 3
work_dir: ./work_dir/ntu_hdgcn/cross-subject/joint_CoM_1/

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /cvhci/temp/prgc/hdgcn_filtered/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 32
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  bone: False

test_feeder_args:
  data_path: /cvhci/temp/prgc/hdgcn_filtered/NTU60_CS.npz
  split: test
  window_size: 32
  p_interval: [0.95]
  bone: False
  debug: False

# model
model: model.HDGCN.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 1

#optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 5

# training
device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 50
nesterov: True
