# command line: main.py --config /home/prgc/acrionreco-with-noisy-data-topic-c/HD-GCN/config/nturgbd-cross-subject/joint_com_1.yaml --device 0

base_lr: 0.1
batch_size: 16
config: /home/prgc/acrionreco-with-noisy-data-topic-c/HD-GCN/config/nturgbd-cross-subject/joint_com_1.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
loss_type: CE
lr_decay_rate: 0.1
lr_ratio: 0.001
model: model.HDGCN.Model
model_args:
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    CoM: 1
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 50
num_worker: 3
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 16
test_feeder_args:
  bone: false
  data_path: /cvhci/temp/prgc/hdgcn_filtered/NTU60_CS.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  window_size: 32
train_feeder_args:
  bone: false
  data_path: /cvhci/temp/prgc/hdgcn_filtered/NTU60_CS.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  window_size: 32
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/ntu_hdgcn/cross-subject/joint_CoM_1/
